source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TouchableScrollView_Example' do
  pod 'TouchableScrollView', :path => '../'
end

target 'TouchableScrollView_Tests' do
  pod 'TouchableScrollView', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
